# escape=`

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && `
    apt install -y --no-install-recommends curl ca-certificates libsqlite3-mod-spatialite libspatialite-dev git build-essential && `
    ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite && `
    rm -rf /var/lib/apt/lists/*

# Install UV to manage Python versions and venvs
ADD https://astral.sh/uv/0.6.5/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Create venvs (and install python versions), use source venv-py310/bin/activate to activate
RUN uv venv --python 3.9  venv-py39  && `
    uv venv --python 3.10 venv-py310 && `
    uv venv --python 3.11 venv-py311 && `
    uv venv --python 3.12 venv-py312

# Install AequilibraE for its dependencies, then remove it
COPY aequilibrae aequilibrae
RUN for version in 3.9 3.10 3.11 3.12; do `
        . venv-py${version//./}/bin/activate && `
        uv pip install -r aequilibrae/requirements.txt -r aequilibrae/tests/requirements_tests.txt -r aequilibrae/docs/requirements-docs.txt && `
        deactivate; `
    done

RUN rm -rf aequilibrae
