# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Set PowerShell as the default shell
SHELL ["powershell", "-Command"]

# Download channel for fixed install.
ARG CHANNEL_URL=https://aka.ms/vs/17/release/channel
ADD ${CHANNEL_URL} C:\TEMP\VisualStudio.chman

# Download and install Build Tools for Visual Studio 2022 for native desktop workload.
ADD https://aka.ms/vs/17/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended `
    --installPath C:\BuildTools

# Install 7-zip to extract SpatiaLite files
RUN Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2201-x64.exe -OutFile 7z-installer.exe; `
    Start-Process -FilePath .\7z-installer.exe -ArgumentList '/S' -Wait; `
    Remove-Item -Path .\7z-installer.exe

# Download and extract SpatiaLite
RUN Invoke-WebRequest -Uri http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-5.1.0-win-amd64.7z -OutFile mod_spatialite.7z; `
    & 'C:\Program Files\7-Zip\7z.exe' x mod_spatialite.7z -oC:\spatialite; `
    Remove-Item -Path .\mod_spatialite.7z; `
    setx /M PATH "$env:PATH;C:\spatialite"

# Install UV to manage Python versions and venvs
RUN powershell -ExecutionPolicy Bypass -Command "irm https://astral.sh/uv/install.ps1 | iex"

# Create venvs (and install python versions), use venv-py310\Scripts\activate to activate
RUN uv venv --python 3.9  venv-py39; `
    uv venv --python 3.10 venv-py310; `
    uv venv --python 3.11 venv-py311; `
    uv venv --python 3.12 venv-py312

COPY aequilibrae aequilibrae
# Install AequilibraE for its dependencies, then remove it
RUN venv-py39\Scripts\activate;  uv pip install -r aequilibrae/requirements.txt -r aequilibrae/tests/requirements.txt; deactivate; `
    venv-py310\Scripts\activate; uv pip install -r aequilibrae/requirements.txt -r aequilibrae/tests/requirements.txt; deactivate; `
    venv-py311\Scripts\activate; uv pip install -r aequilibrae/requirements.txt -r aequilibrae/tests/requirements.txt; deactivate; `
    venv-py312\Scripts\activate; uv pip install -r aequilibrae/requirements.txt -r aequilibrae/tests/requirements.txt; deactivate
