# escape=`

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && `
    apt install -y --no-install-recommends curl ca-certificates libsqlite3-mod-spatialite libspatialite-dev git && `
    ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite

# Install UV to manage Python versions and venvs
ADD https://astral.sh/uv/0.6.5/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Create venvs (and install python versions), use source venv-py310/bin/activate to activate
RUN uv venv --python 3.10 venv-py310 && `
    uv venv --python 3.11 venv-py311 && `
    uv venv --python 3.12 venv-py312 && `
    uv venv --python 3.13 venv-py313

# Install AequilibraE for its dependencies, then remove it
RUN venv-py310/bin/activate && uv pip install aequilibrae && uv pip uninstall aequilibrae && deactivate && `
    venv-py311/bin/activate && uv pip install aequilibrae && uv pip uninstall aequilibrae && deactivate && `
    venv-py312/bin/activate && uv pip install aequilibrae && uv pip uninstall aequilibrae && deactivate && `
    venv-py313/bin/activate && uv pip install aequilibrae && uv pip uninstall aequilibrae && deactivate
