name: Build Windows Docker Image for AequilibraE CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and Push
        shell: powershell
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/windows-ci:latest -f Dockerfile-windows-ci ci/aequilibrae/
          docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/windows-ci:latest
